config/routes.rb
RailstutApp::Application.routes.draw do
  get "static_pages/home"
  get "static_pages/help"
  get "static_pages/about"

  get "/signup", to: "users#new", as: "signup"
  get "/help", to: "static_pages#help", as: "help"
  get "/about", to: "static_pages#about", as: "about"
  get "/contact", to: "static_pages#contact", as: "contact"
  get "/signin", to: "sessions#new", as: "signin"

  match "/signout" => "sessions#destroy", via: "delete"

  resources :users do
    member do
      get :following, :followers, :feed
    end
  end
  resources :sessions
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

  root "static_pages#home"
  

  

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
	belongs_to :user 
	default_scope -> { order('created_at DESC') }
	validates :content, presence: true, length: { maximum: 140 }
	validates :user_id, presence: true

	def self.from_users_followed_by(user)
		followed_user_ids = "SELECT followed_id FROM relationships
						     WHERE follower_id = :user_id"
		where("user_id IN (#{followed_user_ids}) OR user_id = :user_id ", user_id: user.id)
	end
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
	belongs_to :follower, class_name: "User"
	belongs_to :followed, class_name: "User"
	validates :follower_id, presence: true
	validates :followed_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :microposts
	before_save { self.email = email.downcase }
	validates :name, presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
	                  uniqueness: { case_sensitive: true }
	validates :password, length: { minimum: 6 } 
	has_secure_password

	has_many :relationships, foreign_key: "follower_id", dependent: :destroy
	has_many :followed_users, through: :relationships, source: :followed
	has_many :reverse_relationships, foreign_key: "followed_id", class_name: "Relationship",
	                                 dependent: :destroy
	has_many :followers, through: :reverse_relationships	                             

	before_create :create_remember_token

	def User.new_remember_token
		SecureRandom.urlsafe_base64
	end

	def User.encrypt(token)
		Digest::SHA1.hexdigest(token.to_s)
	end

	def feed
		Micropost.from_users_followed_by(self)
	end

	def following?(user)
		relationships.find_by(followed_id: user.id)
	end

	def follow!(user)
		relationships.create!(followed_id: user.id)
	end

	def unfollow!(user)
		relationships.find_by(followed_id: user.id).destroy!
	end

	private

		def create_remember_token
			self.remember_token = User.encrypt(User.new_remember_token)
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include SessionsHelper

end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController

	before_action :signed_in_user, only: [:create, :destroy]
	before_action :correct_user, only: [:destroy]

	def create
		@micropost = current_user.microposts.build(micropost_params)
		if @micropost.save
			flash[:success] = "Micropost created!"
			redirect_to root_path
		else
			@feed_items = []
			render 'static_pages/home'
		end
	end

	def destroy
		@micropost = current_user.microposts.find_by(id: params[:id])
		@micropost.destroy
		redirect_to root_path
	end

	private

		def micropost_params
			params.require(:micropost).permit(:content)
		end

		def correct_user
			@micropost = current_user.microposts.find_by(id: params[:id])
			redirect_to root_path if @micropost.nil?
		end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
	before_action :signed_in_user

	def create
		@user = User.find(params[:relationship][:followed_id])
		current_user.follow!(@user)
		respond_to do |format|
			format.html { redirect_to @user }
			format.js
		end
	end

	def destroy
		@user = Relationship.find(params[:id]).followed
		current_user.unfollow!(@user)
		respond_to do |format|
			format.html { redirect_to @user }
			format.js
		end
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by(email: params[:email])
  	if user && user.authenticate(params[:password])
  		sign_in user
  		flash[:success] = "You are now signed in."
      redirect_back_or user      
  	else
  		flash.now[:error] = "Invalid email/password combination."
  		render 'new'
  	end
  end

  def destroy
  	flash[:success] = "You are now signed out."
  	sign_out
  	redirect_to root_path
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	if current_user
  		@micropost = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])  		
  	end
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :signed_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: [:destroy]

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		sign_in @user
  		flash[:success] = "Welcome to the Rails Drills App!"
  		redirect_to @user
  	else
  		render 'new'
  	end
  end

  def index
    @users = User.paginate(page: params[:page])
  end

  def show
  	@user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      sign_in @user
      flash[:success] = "Profile updated successfully."
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id]).destroy
    redirect_to users_path
  end

  def following
    @title = "Following"
    @user = User.find(params[:id])
    @users = @user.followed_users.paginate(page: params[:page])
    @users_all = @user.followed_users
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    @users_all = @user.followers
    render 'show_follow'
  end

  def feed
    @title = "Feed"
    @user = User.find(params[:id])
    @feed_items = @user.feed.paginate(page: params[:page])
  end

  private

  	def user_params
  		params.require(:user).permit(:name, :email, :password, :password_confirmation)
  	end  

    def correct_user
      @user = User.find(params[:id])
      redirect_to root_path unless current_user?(@user)
    end

    def admin_user
      @user = User.find(params[:id])
      redirect_to root_path unless current_user.admin?
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def sign_in(user)
		remember_token = User.new_remember_token
		cookies.permanent[:remember_token] = remember_token
		user.update_attribute(:remember_token, User.encrypt(remember_token))
		self.current_user = user
	end

	def current_user=(user)
		@current_user = user
	end

	def current_user
		remember_token = User.encrypt(cookies[:remember_token])
		@current_user ||= User.find_by(remember_token: remember_token)
	end

	def signed_in_user
      unless signed_in?
        store_location
        redirect_to signin_path, notice: "Please sign in."
      end
    end  

	def signed_in?
		!current_user.nil?
	end

	def sign_out
		self.current_user = nil
		cookies.delete(:remember_token)
	end

	def current_user?(user)
		current_user == user
	end

	def store_location
		session[:return_to] = request.url
	end

	def redirect_back_or(default)
		redirect_to(session[:return_to] || default)
		session.delete(:return_to)
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
	def gravatar_for(user, options = { size: 50 })
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		size = options[:size]
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
		image_tag(gravatar_url, alt: user.name, class: "gravatar")
	end
end

app/views/layouts/_footer.html.erb
<footer>
	<small>
		Rails Drills by John Howlett
	</small>
	<ul>
		<li><%= link_to "About", about_path %></li>
		<li><%= link_to "Contact", contact_path %></li>
	</ul>
</footer>	

app/views/layouts/_header.html.erb
<header>
<div class="container">
	<%= link_to "sample app", root_path, id: "logo" %>
	<nav>
		<ul class="nav nav-tabs pull-right">
			<li><%= link_to "Home", root_path %></li>
			<li><%= link_to "Help", help_path %></li>
			<% if signed_in? %>
				<li><%= link_to "Users", users_path %></li>
				<li id="fat-menu" class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle= "dropdown">Account <b class="caret"></b></a>
					<ul class="dropdown-menu">
						<li><%= link_to "Profile", current_user %></li>
						<li><%= link_to "Settings", edit_user_path(current_user) %></li>
						<li class="divider"></li>
						<li><%= link_to "Sign Out", signout_path, method: :delete %></li>
					</ul>
				</li>
			<% else %>
				<li><%= link_to "Sign In", signin_path %></li>
			<% end %>
		</ul>
	</nav>
</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>"Rails Tutorial Sample App | <%= yield(:title) %>"</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<!--
	 <svg xmlns='http://www.w3.org/2000/svg' width='100%' height='100%'>
		<defs>
			<pattern patternUnits='userSpaceOnUse' id='c' width='#f0f0f0' height='NaN' x='0' y='0' viewBox='0 0 5 10'>
				<line x1='-2' y1='1' x2='7' y2='10' stroke='#ffffff' stroke-width='#9bbddb'/>
				<line x1='-2' y1='6' x2='7' y2='15' stroke='#ffffff' stroke-width='#9bbddb'/>
				<line x1='-2' y1='-4' x2='7' y2='5' stroke='#ffffff' stroke-width='#9bbddb'/>
			</pattern>
			<radialGradient id='g' gradientUnits='userSpaceOnUse' cx='50%' cy='50%' r='75%' fx='46%' fy='22%'>
				<stop offset='0%' stop-opacity='.2' stop-color='#ffffff' />
				<stop offset='100%' stop-color='#9bbddb' />
			</radialGradient>
		</defs>
		<rect width='100%' height='100%' fill='url(#c)'/>
		<rect width='120%' x='-10%' y='-10%' height='120%' fill='url(#g)'/>
	</svg>
	-->

	<%= render 'layouts/header' %>
	<div id="section_1"><p>hello</p></div>
	<div id="section_2"><p>hello</p></div>
	<div id="section_3"><p>hello</p></div>
	<div class="container">
		<% flash.each do |key, value| %>
			<%= content_tag(:div, value, class: "alert alert-#{key}") %>
		<% end %>
		<%= yield %>
		<%= render 'layouts/footer' %>
		<%= debug(params) if Rails.env.development? %>
	</div>
</body>
</html>

app/views/microposts/_micropost.html.erb
<% if @user.microposts.any? %>
	<li>
		<span class="content">
			<%= micropost.content %>
		</span>
		<span class="timestamp">
			Posted <%= time_ago_in_words(micropost.created_at) %> ago.
		</span>
		<% if current_user?(micropost.user) %>
			<%= link_to "delete", micropost, method: :delete, confirm: "Are you sure?" %>
		<% end %>
	</li>
<% end %>

app/views/relationships/create.js.erb
$('#follow_form').html("<%= escape_javascript(render 'users/unfollow') %>");
$('#followers').html("<%= @user.followers.count %>");

app/views/relationships/destroy.js.erb
$('#follow_form').html("<%= escape_javascript(render 'users/follow') %>");
$('#followers').html("<%= @user.followers.count %>");

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
	<div class="error_explanation">
		<div class="alert alert-error">
			This form has <%= pluralize(object.errors.count, "error") %>.
		</div>
		<ul>
			<% object.errors.full_messages.each do |msg| %>
				<li><%= msg %>.</li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
	<ol class="microposts">
		<%= render partial: 'shared/feed_item', collection: @feed_items %>
	</ol>
	<%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li class="<%= feed_item.id %>">
	<span class="user">
		<%= link_to feed_item.user.name, feed_item.user %>
	</span>
	<span class="content">
		<%= feed_item.content %>
	</span>
	<span class="timestamp">
		Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
	</span>
	<% if current_user?(feed_item.user) %>
		<%= link_to "delete", feed_item, method: :delete, confirm: "Are you sure?" %>
	<% end %>
</li>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
	<%= render 'shared/error_messages', object: f.object %>
	<%= f.text_area :content, placeholder: "Compose new micropost..." %>
	<%= f.submit "Post", class: "btn btn-primary btn-large" %>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
	<a href="<%= following_user_path(@user) %>">
		<strong id="following" class="stat">
			<%= @user.followed_users.count %>
		</strong>
		 following
	</a>
	<a href="<%= followers_user_path(@user) %>">
		<strong id="followers" class="stat">
			<%= @user.followers.count %>
		</strong>
		 followers
	</a>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 52), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "View my Profile", current_user %></span>
<span><%= pluralize(current_user.microposts.count, "Micropost") %></span>

app/views/static_pages/about.html.erb
<%=  provide(:title, "About")  %>

<h1>About</h1>

<p>This is a Ruby on Rails tutorial</p>

app/views/static_pages/contact.html.erb
<%=  provide(:title, "Contact")  %>

<h1>Contact</h1>

<p>Contact the Rails Drills creator at creator@email.com</p>

app/views/static_pages/help.html.erb
<%=  provide(:title, "Help")  %>

<h1>Help</h1>

<p>This is the help page for the <%= link_to "Rails Tutorial Sample App", "http://www.railstutorial.com/help" %></p>

app/views/static_pages/home.html.erb
<% if signed_in? %>

	<div class="row">
		<aside class="span4">
			<section>
				<%= render 'shared/user_info' %>
			</section>
			<section>
				<%= render 'shared/stats' %>
			</section>
			<section>
				<%= render 'shared/micropost_form' %>
			</section>
		</aside>
		<div class="span8">
			<h3>Micropost Feed</h3>
			<%= render 'shared/feed' %>
		</div>
	</div>

<% else %>

	<%=  provide(:title, "Home")  %>

	<div class= "center hero-unit">
		<h1>Welcome to the Rails Drills App</h1>

		<p>This is the home page for the <%= link_to "Rails Drills App", "http://www.railstutorial.com/" %></p>
		<%= link_to "Sign Up Now!", signup_path, class: "btn btn-primary" %>
	</div>

<% end %>

app/views/users/_fields.html.erb
<%= render 'shared/error_messages', object: f.object %>

			<%= f.label :name %>
			<%= f.text_field :name %>

			<%= f.label :email %>
			<%= f.text_field :email %>

			<%= f.label :password %>
			<%= f.password_field :password %>

			<%= f.label :password_confirmation, "Confirmation" %>
			<%= f.password_field :password_confirmation %>

app/views/users/_follow.html.erb
<%= form_for(current_user.relationships.build(followed_id: @user.id), remote: true) do |f| %>
	<div><%= f.hidden_field :followed_id %></div>
	<%= f.submit "Follow", class: "btn btn-large btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
	<div id="follow_form">
		<% if current_user.following?(@user) %>
			<%= render 'unfollow' %>
		<% else %>
			<%= render 'follow' %>
		<% end %>
	</div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.relationships.find_by(followed_id: @user.id), html: { method: :delete }, remote: true) do |f| %>
	<%= f.submit "Unfollow", class: "btn btn-large" %>
<% end %>

app/views/users/_user.html.erb
<li>
	<%= gravatar_for user, size: 52 %>
	<%= link_to user.name, user %>
</li>

app/views/users/edit.html.erb
<%= provide(:title, "Edit") %>

<div class="row">
	<div class="span6 offset3">
	
		<h1>Sign up</h1>

		<%= form_for(@user) do |f| %>

			<%= render 'fields', f: f %>
			<br>
			<%= f.submit "Create my Account", class: "btn btn-primary" %>

		<% end %>
		<%= gravatar_for @user %>
		<%= link_to "Change", "http://gravatar.com/emails" %>
	</div>
</div>

app/views/users/feed.html.erb
<div class="row">
	<aside class="span4">
		<%= render 'shared/user_info' %>
		<section>
			<%= render 'shared/stats' %>
		</section>
	</aside>
	<div class="span8">
		<h3>
			<%= @user.name %>'s Feed
		</h3>
		<%= render 'shared/feed' %>
	</div>
</div>

app/views/users/index.html.erb
<%= provide(:title, "Users Index") %>

<%= will_paginate %>

<ul class="users">
	<%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<%= provide(:title, "Sign Up") %>

<div class="row">
	<div class="span6 offset3">
	
		<h1>Sign up</h1>

		<%= form_for(@user) do |f| %>

			<%= render 'shared/error_messages' %>

			<%= f.label :name %>
			<%= f.text_field :name %>

			<%= f.label :email %>
			<%= f.text_field :email %>

			<%= f.label :password %>
			<%= f.password_field :password %>

			<%= f.label :password_confirmation, "Confirmation" %>
			<%= f.password_field :password_confirmation %>

			<br>
			<%= f.submit "Create my Account", class: "btn btn-primary" %>

		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<%= provide(:title, @user.name) %>

<div class="row">
	<aside class="span4">
		<section>
			<h1>
				<%= gravatar_for @user %>
				<%= @user.name %>
			</h1>
		</section>
		<section>
			<%= render 'shared/stats' %>
		</section>
		<section>
			<%= link_to "Feed", feed_user_path(@user) %>
		</section>
	</aside>
	<%= render 'follow_form' %>
	<div class="span8">
		<h3>Microposts (<%= @user.microposts.count %>)</h3>
		<ol class="microposts">
			<%= render @microposts %>
		</ol>
		<%= will_paginate @microposts %>
	</div>
</div>

app/views/users/show_follow.html.erb
<%= provide(:title, @title) %>
<%= gravatar_for @user, size: 52 %>
<div class="row">
	<aside class="span4">
		<h1><%= @user.name %></h1>
		<span><%= link_to "View my Profile", @user %></span>
		<span>
			<strong>
				Microposts:
			</strong>
			 <%= @user.microposts.count %>
		</span>
		<section>
			<%= render 'shared/stats' %>
		</section>
		<section>
			<div class="user_avatars">
				<% if @users.any? %>
					<% @users_all.each do |user| %>
						<%= link_to gravatar_for(user, size: 30), user %>
					<% end %>
				<% end %>
			</div>
		</section>
	</aside>
	<div class="span8">
		<h1><%= @title %></h1>
		<% if @users.any? %>
			<ul class="users">
				<%= render @users %>
			</ul>
			<%= will_paginate %>
		<% end %>
	</div>
</div>